config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :backgrounds do
    resources :medicines, on: :collection
    resources :allergies, on: :collection
  end

  resources :past_medical_histories
  resources :present_illnesses
  resources :reviews

  root "top#index"
   if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
      resources :posts, param: :slug
    end

end

app/models/past_medical_history.rb
class PastMedicalHistory < ActiveRecord::Base
  belongs_to :background
end

app/controllers/past_medical_histories_controller.rb
class PastMedicalHistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_past_medical_history, only: [:show, :edit, :update, :destroy]

  def index
    @past_medical_histories = PastMedicalHistory.all
    @past_medical_histories.each do |past_medical_history|
      if past_medical_history.background_id == current_user.background.id
        @past_medical_history = past_medical_history
      end
    end
  end

  def new
    @past_medical_history = PastMedicalHistory.new
  end

  def create
    @past_medical_history = PastMedicalHistory.new(histories_params)
    @past_medical_history.background_id = current_user.background.id
      if @past_medical_history.save
        redirect_to past_medical_histories_path, notice:"Your registration has been compleated"
      else
        render "new" if @past_medical_history.invalid?
      end
  end

  def edit
  end

  def update
    @past_medical_history.update(histories_params)
    if @past_medical_history.invalid?
      render "edit"
    else
      redirect_to past_medical_histories_path
    end
  end

  def destroy
    if @past_medical_history.destroy
      redirect_to past_medical_histories_path, notice:"Past medical history has been deleted"
    end
  end

private

  def histories_params
    params.require(:past_medical_history).permit(:icd_code,:brain_disease_in_the_past,:heart_disease_in_the_past,:surgery_in_the_past,:hospitalized_in_the_past,:attending_to_a_hospital_now)
  end

  def set_past_medical_history
    @past_medical_history = PastMedicalHistory.find(params[:id])
  end

end

app/helpers/past_medical_histories_helper.rb
module PastMedicalHistoriesHelper
end

app/views/past_medical_histories/_form.html.erb
<div class="container-main col-sm-12 col-md-12 col-lg-12">
  <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
  <div class="wrapper-bg-form col-md-6 col-md-offset-3">
    <%= form_for(@past_medical_history) do |f| %>

    <% if @past_medical_history.errors.any? %>
      <div id= "error_explanation">
        <h2 class= "text-danger"><%= @past_medical_history.errors.count %> errors have been detected</h2>
        <ul>
          <% @past_medical_history.errors.full_messages.each do |msg| %>
            <li class= "text-danger"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <span class="badge badge-info">Your past medical history info</span>
      <div class="blockquote ">

        <div class= "form-group" >
          <%= f.label :icd_code %>
          <div class="items_arrange">
            <%= f.text_field :icd_code, class:"form-control", placeholder:"Name" %>
          </div>
        </div>

        <%= f.hidden_field :background_id %>
        <div class= "form-group" >
          <%= f.label :brain_disease_in_the_past,"Have you ever had brain disease in the past?", {class: 'form-label'} %>
          <div class="items_arrange">
            <%= f.radio_button :brain_disease_in_the_past, true %> Yes
            <%= f.radio_button :brain_disease_in_the_past, false, {} %> No
          </div>
        </div>

        <%= f.hidden_field :background_id %>
        <div class= "form-group" >
          <%= f.label :heart_disease_in_the_past,"Have you ever had heart disease in the past?", {class: 'form-label'} %>
          <div class="items_arrange">
            <%= f.radio_button :heart_disease_in_the_past, true %> Yes
            <%= f.radio_button :heart_disease_in_the_past, false, {} %> No
          </div>
        </div>

        <%= f.hidden_field :background_id %>
        <div class= "form-group" >
          <%= f.label :surgery_in_the_past,"Have you ever had surgery in the past?", {class: 'form-label'} %>
          <div class="items_arrange">
            <%= f.radio_button :surgery_in_the_past, true %> Yes
            <%= f.radio_button :surgery_in_the_past, false, {} %> No
          </div>
        </div>

        <%= f.hidden_field :background_id %>
        <div class= "form-group" >
          <%= f.label :hospitalized_in_the_past,"Have you ever been hospitalized in the past?", {class: 'form-label'} %>
          <div class="items_arrange">
            <%= f.radio_button :hospitalized_in_the_past, true %> Yes
            <%= f.radio_button :hospitalized_in_the_past, false, {} %> No
          </div>
        </div>

        <%= f.hidden_field :background_id %>
        <div class= "form-group" >
          <%= f.label :attending_to_a_hospital_now,"Are you attending to a hospital now?", {class: 'form-label'} %>
          <div class="items_arrange">
            <%= f.radio_button :attending_to_a_hospital_now, true %> Yes
            <%= f.radio_button :attending_to_a_hospital_now, false, {} %> No
          </div>
        </div>

      </div>

        <div class="wrapper-bg-form-submit">
          <%= link_to "Back to your past_medical_history info", past_medical_histories_path, class:"btn btn-neutral" %>
          <%= f.submit 'Register', class: 'btn btn-primary' %>
        </div>

        <% end %>

      </div>
  </div>
  </div>
  <div class="container-main-last col-xs-12 col-sm-12 col-md-12 col-lg-12">
  </div>

app/views/past_medical_histories/edit.html.erb
<div class="container-head col-sm-12 col-md-12 col-lg-12">
  <h1><span class="under">past_medical_history</span></h1>
  <div class="container-head-content col-sm-12 col-md-12 col-lg-12">
  <h3>
    You can edit your past medical history information here.
  </h3>
  </div>
</div>

  <%= render 'form' %>

app/views/past_medical_histories/index.html.erb
<div class="container-head col-sm-12 col-md-12 col-lg-12">
  <h1><span class="under">Past Medical History</span></h1>
</div>
  <!-- <div class="container-head-content col-sm-12 col-md-12 col-lg-12"> -->
    <div class="container-main col-sm-12 col-md-12 col-lg-12">
      <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
        <div class="wrapper-bg-form col-md-6 col-md-offset-3">

        <% if notice.nil? == false %>
        <div class="alert alert-success" role="alert">
        	<div class="container">
        		<div class="alert-icon">
        			<i class="now-ui-icons ui-2_like"></i>
        		</div>
        		<strong>Well done!</strong> Your registration has been successfully compleated.
        		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
        				<span aria-hidden="true">
        				<i class="now-ui-icons ui-1_simple-remove"></i>
        			</span>
        		</button>
        	</div>
        </div>
        <% end %>

        <% if @past_medical_history.nil? == false %>
          <span class="badge badge-info">Your Past Medical History</span>
            <div class="blockquote ">
              <div class= "form-group" >
                <strong> ICD code </strong>
                <div class="items_arrange">
                  <%= @past_medical_history.icd_code %>
                </div>
              </div>

              <div class= "form-group" >
                <strong> Have you ever had brain disease in the past? </strong>
                <div class="items_arrange">
                  <% if @past_medical_history.brain_disease_in_the_past == true %>
                    <%= "Yes" %>
                  <% else @past_medical_history.brain_disease_in_the_past == false %>
                    <%= "No" %>
                  <% end %>
                </div>
              </div>

              <div class= "form-group" >
                <strong> Have you ever had heart disease in the past? </strong>
                <div class="items_arrange">
                  <% if @past_medical_history.heart_disease_in_the_past == true %>
                    <%= "Yes" %>
                  <% else @past_medical_history.heart_disease_in_the_past == false %>
                    <%= "No" %>
                  <% end %>
                </div>
              </div>

              <div class= "form-group" >
                <strong> Have you ever had surgery in the past? </strong>
                <div class="items_arrange">
                  <% if @past_medical_history.surgery_in_the_past == true %>
                    <%= "Yes" %>
                  <% else @past_medical_history.surgery_in_the_past == false %>
                    <%= "No" %>
                  <% end %>
                </div>
              </div>

              <div class= "form-group" >
                <strong> Have you ever been hospitalized in the past? </strong>
                <div class="items_arrange">
                  <% if @past_medical_history.hospitalized_in_the_past == true %>
                    <%= "Yes" %>
                  <% else @past_medical_history.hospitalized_in_the_past == false %>
                    <%= "No" %>
                  <% end %>
                </div>
              </div>

              <div class= "form-group" >
                <strong> Are you attending to a hospital now? </strong>
                <div class="items_arrange">
                  <% if @past_medical_history.attending_to_a_hospital_now == true %>
                    <%= "Yes" %>
                  <% else @past_medical_history.attending_to_a_hospital_now == false %>
                    <%= "No" %>
                  <% end %>
                </div>
              </div>

          </div>

            <%= link_to "Edit", edit_past_medical_history_path(@past_medical_history), class:"btn btn-info" %>
            <%= link_to "Delete", past_medical_history_path(@past_medical_history), class:"btn btn-default", method: :delete, data:{confirm:"Are you sure to delete?"}%>

        <% elsif @past_medical_history.nil? == true && current_user.background.nil? == false %>
          <span class="badge badge-info">Your Past Medical History</span>
            <div class="blockquote ">
              <h4>Please register your background info first then, you are able to add past medical history.</h4>
            </div>
          </span>
            <%=  link_to "Register", new_past_medical_history_path, class:"btn btn-info" %>
        <% else %>
          <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
              <h4>Please register your background info first then, you are able to add past medical history.</h4>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    <div class="container-main-last col-sm-12 col-md-12 col-lg-12">
    </div>

app/views/past_medical_histories/new.html.erb
<div class="container-head col-sm-12 col-md-12 col-lg-12">
<h1><span class="under">Past Medical History</span></h1>
  <div class="container-head-content col-sm-12 col-md-12 col-lg-12">
  <h3>
    You can register your Past Medical History information here.
  </h3>
  </div>
</div>

  <%= render 'form' %>

  <div class="container-main-last col-xs-12 col-sm-12 col-md-12 col-lg-12">
  </div>