config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :backgrounds do
    resources :medicines, on: :collection
    resources :allergies, on: :collection
  end

  resources :past_medical_histories
  resources :present_illnesses
  resources :reviews

  root "top#index"
   if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
      resources :posts, param: :slug
    end

end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  belongs_to :background
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController

  def create
    @medicine = current_user.background.medicines.build(medicines_params)
    # @background = @medicine.background
    # @medicines = @background.medicines

    respond_to do |format|
      if @medicine.save
        format.html {redirect_to backgrounds_path}
        format.js {render :index}
      else
        format.html {render :index}
      end
    end
  end

  def destroy

    @medicine = Medicine.find(params[:id])
    respond_to do |format|
      if @medicine.destroy
        format.html {redirect_to backgrounds_path}
        format.js {render :index}
      else
        format.html {render :index}
      end
    end
  end

  private

    def medicines_params
      params.require(:medicine).permit(:background_id, :medicine_name)
    end


end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_for([background, medicine], remote: true) do |f| %>
  <% if medicine.errors.any? %>
  <div id= "error_explanation" >
    <h2> <%= medicine.errors.count %>件のエラーがあります</h2>
    <ul>
      <%= medicine.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.hidden_field :background_id %>
  <div class= "form-group" >
    <div class="items_arrange">
      <%= f.text_field :medicine_name, class:"form-control", placeholder:"Please type medicine Names" %>
    </div>
  </div>

  <div class="wrapper-bg-form-submit">
    <%= f.submit 'Add', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/medicines/_index.html.erb
<ul>
  <% medicines.each do |medicine| %>
    <% unless medicine.id.nil? %>
    <div class="medicine">
      <span class="badge badge-info"><%= medicine[:medicine_name] %></span>
      <%= link_to "", background_medicine_path(medicine.background, medicine), class:"glyphicon glyphicon-remove text-muted", method: :delete, remote: true, data:{confirm:"are you sure to remove?"} %>
    </div>
    <% end %>
  <% end %>
</ul>

app/views/medicines/index.js.erb
$("#medicines_area").html("<%= j(render 'medicines/index', { medicines: @medicine.background.medicines, background: @medicine.background }) %>")
$(':text').val('')