config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :backgrounds do
    resources :medicines, on: :collection
    resources :allergies, on: :collection
  end

  resources :past_medical_histories
  resources :present_illnesses
  resources :reviews

  root "top#index"
   if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
      resources :posts, param: :slug
    end

end

app/models/background.rb
class Background < ActiveRecord::Base

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :country, presence: true
  validates :occupation, presence: true
  validates :religion, presence: true
  validates :living_will, presence: true

  belongs_to :user
  has_many :medicines, dependent: :destroy
  has_many :allergies, dependent: :destroy
  has_one :past_medical_history, dependent: :destroy
  has_one :review, dependent: :destroy

end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_background, only:[:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @backgrounds = Background.all
      @backgrounds.each do |background|
        if background.user_id == current_user.id
          @background = current_user.background
          @medicines = background.medicines
          @medicine = background.medicines.build
          @allergies = background.allergies
          @allergy = background.allergies.build
        end
      end
    end
  end

  def new
    @background = Background.new
  end

  def edit

  end

  def create
    @background = Background.new(backgrounds_params)
    @background.user_id = current_user.id
    if @background.save
      redirect_to backgrounds_path, notice:"Your registration has been compleated"
    else
      render "new" if @background.invalid?
    end
  end

  def update
    @background.update(backgrounds_params)
    if @background.invalid?
      render 'edit'
    else
      redirect_to backgrounds_path
    end
  end

  def destroy
    @background.destroy
    redirect_to backgrounds_path
  end

  private

    def backgrounds_params
      params.require(:background).permit(:name, :age, :sex, :country, :occupation, :religion, :living_will, :notes)
    end

    def set_background
      @background = Background.find(params[:id])
    end

end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/views/backgrounds/_form.html.erb
<div class="container-main col-sm-12 col-md-12 col-lg-12">
  <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
  <div class="wrapper-bg-form col-md-6 col-md-offset-3">
    <%= form_for(@background) do |f| %>

    <% if @background.errors.any? %>
      <div id= "error_explanation">
        <h2 class= "text-danger"><%= @background.errors.count %> errors have been detected</h2>
        <ul>
          <% @background.errors.full_messages.each do |msg| %>
            <li class= "text-danger"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <span class="badge badge-info">Your background info</span>
      <div class="blockquote ">

        <div class= "form-group" >
          <%= f.label :Name %>
          <div class="items_arrange">
            <%= f.text_field :name, class:"form-control", placeholder:"Name" %>
          </div>
        </div>

        <div class= "form-group" >
          <%= f.label :Age %>
          <div class="items_arrange">
            <%= f.text_field :age, class:"form-control", placeholder:"Age" %>
            <%#= f.select :age, Background.ages.keys.to_a %>
            <%#= f.select :age, Background.ages.values.to_a %>

          </div>
        </div>

        <div class= "form-group" >
          <%= f.label :Sex %>
          <div class="items_arrange">
          <%#= f.text_field :sex, class:"form-control", placeholder:"Sex" %>
          <%= f.select :sex, {"Male" => "male", "Female" => "female"} %>
          </div>
        </div>

        <div class= "form-group" >
          <%= f.label :Country %>
          <div class="items_arrange">
            <%= f.text_field :country, class:"form-control", placeholder:"Country" %>
          </div>
        </div>

        <div class= "form-group" >
          <%= f.label :Occupation %>
          <div class="items_arrange">
            <%= f.text_field :occupation, class:"form-control", placeholder:"Occupation" %>
          </div>
        </div>

        <div class= "form-group" >
          <%= f.label :Religion %>
          <div class="items_arrange">
            <%= f.text_field :religion, class:"form-control", placeholder:"Religion" %>
          </div>
        </div>

        <div class= "form-group" >
          <%= f.label :Living_will %>
          <div class="items_arrange">
            <%= f.select :living_will, {"Yes" => "Yes", "No" => "No"} %>
            <%#= f.text_field :living_will, class:"form-control", placeholder:"Living_will" %>
          </div>
        </div>

        <div class= "form-group" >
          <%= f.label :Notes %>
            <div class="items_arrange">
              <%= f.text_area :notes, class:"form-control", placeholder:"Notes" %>
            </div>
        </div>

      </div>

      <div class="wrapper-bg-form-submit">
        <%= link_to "Back to your Background info", backgrounds_path, class:"btn btn-neutral" %>
        <%= f.submit 'Register', class: 'btn btn-info' %>
      </div>


  </div>



    <% end %>

  </div>
</div>

app/views/backgrounds/edit.html.erb
<div class="container-head col-sm-12 col-md-12 col-lg-12">
  <h1><span class="under">Background#edit</span></h1>
  <div class="container-head-content col-sm-12 col-md-12 col-lg-12">
  <h3>
    You can edit your background information here.
  </h3>
  </div>
</div>

  <%= render 'form' %>

  <div class="container-main-last col-xs-12 col-sm-12 col-md-12 col-lg-12">
  </div>

app/views/backgrounds/index.html.erb
<div class="container-head col-sm-12 col-md-12 col-lg-12">
  <h1><span class="under">Background info</span></h1>
  <p class="explanations ">
     Please register your background infomation to communicate doctors easier.
     <br> If there is something you would like to write down regarding your background,
     <br> Please write it down at Notes.
  </p>

</div>
<div class="container-main col-sm-12 col-md-12 col-lg-12">
  <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
    <div class="wrapper-bg-form col-md-6 col-md-offset-3">

    <% if notice.nil? == false %>
    <div class="alert alert-success" role="alert">
    	<div class="container">
    		<div class="alert-icon">
    			<i class="now-ui-icons ui-2_like"></i>
    		</div>
    		<strong>Well done!</strong> Your registration has been successfully compleated.
    		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    				<span aria-hidden="true">
    				<i class="now-ui-icons ui-1_simple-remove"></i>
    			</span>
    		</button>
    	</div>
    </div>
    <% end %>

    <span class="badge badge-info">Your background info</span>
      <div class="blockquote ">

        <% if @background.nil? %>
          <h4>Please register your background info first. </h4>
        <% else %>

          <div class= "form-group" >
            <strong> Name </strong>
            <div class="items_arrange">
              <%= @background.name %>
            </div>
          </div>
          <div class= "form-group" >
            <strong> Age </strong>
            <div class="items_arrange">
              <%= @background.age %>
            </div>
          </div>
          <div class= "form-group" >
            <strong> Sex </strong>
            <div class="items_arrange">
              <%= @background.sex %>
            </div>
          </div>
          <div class= "form-group" >
            <strong> Country </strong>
            <div class="items_arrange">
              <%= @background.country %>
            </div>
          </div>
          <div class= "form-group" >
            <strong> Occupation </strong>
            <div class="items_arrange">
              <%= @background.occupation %>
            </div>
          </div>
          <div class= "form-group" >
            <strong> Religion </strong>
            <div class="items_arrange">
              <%= @background.religion %>
            </div>
          </div>
          <div class= "form-group" >
            <strong> Living will </strong>
            <div class="items_arrange">
              <%= @background.living_will %>
            </div>
          </div>
          <div class= "form-group" >
            <strong> Notes </strong>
            <div class="items_arrange">
              <%= @background.notes %>
            </div>
          </div>
        <% end %>

      </div>

    <!-- ログインユーザの登録状況により表示画面を変更 -->
    <% if current_user.background.nil? == true %>
      <%= link_to "Register", new_background_path(@background), class:"btn btn-info"%>
    <% else %>
      <%= link_to "Edit", edit_background_path(@background), class:"btn btn-info" %>
      <%= link_to "Delete", background_path(@background), method: :delete, class:"btn btn-default" %>
    <% end %>

    </div>
  </div>
</div>
  <!-- </div> -->

<% if @background.nil? %>
  <div class="container-main col-sm-12 col-md-12 col-lg-12">
    <h1><span class="under">Medicines</span></h1>
    <p class="explanations ">
      You can  add Medicines you have taken.
    </p>
    <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
      <div class="wrapper-bg-form col-md-6 col-md-offset-3">
        <h4>Please register your background info first then,<br>
         you are able to add medicines.</h4>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-main col-sm-12 col-md-12 col-lg-12">
    <h1><span class="under">Medicines</span></h1>
    <p class="explanations ">
       you can add Medicines you have taken.
    </p>
    <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
      <div class="wrapper-bg-form col-md-6 col-md-offset-3">
      <div id="medicines_area">
        <%= render partial: 'medicines/index', locals: {background: @background, medicines: @medicines} %>
      </div>
        <%= render partial: 'medicines/form', locals: {background: @background, medicine: @medicine} %>
      </div>
    </div>
  </div>
<% end %>


<% if @background.nil? %>
  <div class="container-main-last col-sm-12 col-md-12 col-lg-12">
    <h1><span class="under">Allergies</span></h1>
    <p class="explanations ">
       You can add Allergies you have.
    </p>
    <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
      <div class="wrapper-bg-form col-md-6 col-md-offset-3">
        <h4>Please register your background info first then,<br>
         you are able to add allergies.</h4>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-main-last col-sm-12 col-md-12 col-lg-12">
    <h1><span class="under">Allergies</span></h1>
    <p class="explanations ">
       Please add Allergies you have.
    </p>
    <div class="container-main-content col-sm-12 col-md-12 col-lg-12">
      <div class="wrapper-bg-form col-md-6 col-md-offset-3">
      <div id="allergies_area">
        <%= render partial: 'allergies/index', locals: {background: @background, allergies: @allergies} %>
      </div>
        <%= render partial: 'allergies/form', locals: {background: @background, allergy: @allergy} %>
      </div>
    </div>
  </div>
<% end %>

app/views/backgrounds/new.html.erb
<div class="container-head col-sm-12 col-md-12 col-lg-12">
  <h1>◆Register Your Background info</h1>
  <div class="container-head-content col-sm-12 col-md-12 col-lg-12">
  <h3>
    You can register your background information here.
  </h3>
  </div>
</div>

  <%= render 'form' %>

  <div class="container-main-last col-xs-12 col-sm-12 col-md-12 col-lg-12">
  </div>