config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :backgrounds do
    resources :medicines, on: :collection
    resources :allergies, on: :collection
  end

  resources :past_medical_histories
  resources :present_illnesses
  resources :reviews

  root "top#index"
   if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
      resources :posts, param: :slug
    end

end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  belongs_to :background
end

app/models/background.rb
class Background < ActiveRecord::Base

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :country, presence: true
  validates :occupation, presence: true
  validates :religion, presence: true
  validates :living_will, presence: true

  belongs_to :user
  has_many :medicines, dependent: :destroy
  has_many :allergies, dependent: :destroy
  has_one :past_medical_history, dependent: :destroy
  has_one :review, dependent: :destroy

end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  belongs_to :background
end

app/models/past_medical_history.rb
class PastMedicalHistory < ActiveRecord::Base
  belongs_to :background
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :background

  validates :background_id, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_one :background, dependent: :destroy
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController

  def create
    @allergy = current_user.background.allergies.build(allergies_params)
    respond_to do |format|
      if @allergy.save
        format.html {redirect_to backgrounds_path}
        format.js {render :index}
      else
        format.js{render :index}
      end
    end
  end

  def destroy
    @allergy = Allergy.find(params[:id])
    respond_to do |format|
      if @allergy.destroy
        format.html {redirect_to background_path}
        format.js {render :index}
      else
        format.html {render :index}
      end
    end
  end

  private
    def allergies_params
      params.require(:allergy).permit(:background_id, :allergy_name)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_filter :set_locale

    def set_locale
    I18n.locale = locale
  end

  def locale
    @locale ||= params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    options.merge(locale: locale)
  end




    #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
    PERMISSIBLE_ATTRIBUTES = %i(name)

    protected

      #deviseのストロングパラメーターにカラム追加するメソッドを定義
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
        devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
      end

end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_background, only:[:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @backgrounds = Background.all
      @backgrounds.each do |background|
        if background.user_id == current_user.id
          @background = current_user.background
          @medicines = background.medicines
          @medicine = background.medicines.build
          @allergies = background.allergies
          @allergy = background.allergies.build
        end
      end
    end
  end

  def new
    @background = Background.new
  end

  def edit

  end

  def create
    @background = Background.new(backgrounds_params)
    @background.user_id = current_user.id
    if @background.save
      redirect_to backgrounds_path, notice:"Your registration has been compleated"
    else
      render "new" if @background.invalid?
    end
  end

  def update
    @background.update(backgrounds_params)
    if @background.invalid?
      render 'edit'
    else
      redirect_to backgrounds_path
    end
  end

  def destroy
    @background.destroy
    redirect_to backgrounds_path
  end

  private

    def backgrounds_params
      params.require(:background).permit(:name, :age, :sex, :country, :occupation, :religion, :living_will, :notes)
    end

    def set_background
      @background = Background.find(params[:id])
    end

end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController

  def create
    @medicine = current_user.background.medicines.build(medicines_params)
    # @background = @medicine.background
    # @medicines = @background.medicines

    respond_to do |format|
      if @medicine.save
        format.html {redirect_to backgrounds_path}
        format.js {render :index}
      else
        format.html {render :index}
      end
    end
  end

  def destroy

    @medicine = Medicine.find(params[:id])
    respond_to do |format|
      if @medicine.destroy
        format.html {redirect_to backgrounds_path}
        format.js {render :index}
      else
        format.html {render :index}
      end
    end
  end

  private

    def medicines_params
      params.require(:medicine).permit(:background_id, :medicine_name)
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only:[:edit,:update, :destroy]

  def index
    @reviews = Review.all
    @reviews.each do |review|
      # if current_user.id == review.background_id
      if review.background_id == current_user.background.id
        @review = Review.find_by(background_id: review.background_id)
        @only_true_review = @review.attributes.select{|k, v| v ==  true} # @reviewからattributesで属性をハッシュ形式で取得後にtrueの値のみをインスタンス変数に代入
      end
    end
    set_target_columns
  end

  def new
    @review = Review.new
    set_target_columns # メソッドを呼び出し。# id,background_id, created_at, updated_at を取り除いたReviweモデルのカラム名の配列
  end

  def create
    @review = Review.new(reviews_params)
    @review.background_id = current_user.background.id
    if @review.save
      redirect_to reviews_path
    else
      set_review
      set_target_columns
      render 'index', notice: "review has already been created. "
    end
  end

  def edit
    set_target_columns
  end

  def update
    @review.update(reviews_params)
    redirect_to reviews_path
  end

  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  private

    def set_target_columns # Reviweモデルのカラム名からid,background_id, created_at, updated_at カラムを取り除いた配列を作成するメソッド
      columns = Review.column_names
      @target_columns = columns[2...-2] # HACK: Reviewsテーブルにカラム追加した際に代入する要素がずれる可能性がある
    end

    def set_review
      @reviews = Review.all
      @reviews.each do |review|
        if review.background_id == current_user.background.id
          @review = Review.find_by(background_id: review.background_id)
        end
      end
    end

    def reviews_params
      params.require(:review).permit(Review.column_names.map{|c| c.to_sym})
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def i18n_url_for(options)
    if options[:locale] == I18n.default_locale
      options[:locale] = nil
    end
    url_for(options)
  end

end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/past_medical_histories_helper.rb
module PastMedicalHistoriesHelper
end

app/helpers/present_illnesses_helper.rb
module PresentIllnessesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pocketkarte</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Ui kit start -->
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png">
        <link rel="icon" type="image/png" href="./assets/img/favicon.png">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>Now Ui Kit by Creative Tim</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
        <!--     Fonts and icons     -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
        <!-- CSS Files -->
        <link href="./assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="./assets/css/now-ui-kit.css?v=1.1.0" rel="stylesheet" />

        <!-- CSS Just for demo purpose, don't include it in your project -->
        <!-- <link href="./assets/css/demo.css" rel="stylesheet" /> -->

        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> -->

    </head>

    <nav class="navbar navbar-expand-lg bg-info">
        <div class="container">
            <div class="navbar-translate">
              <%= link_to "Pocket Karte", root_path, class:"navbar-brand" %>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
         	      <span class="navbar-toggler-bar bar1"></span>
      	        <span class="navbar-toggler-bar bar2"></span>
      	        <span class="navbar-toggler-bar bar3"></span>
       	    </button>
            </div>

            <div class="collapse navbar-collapse justify-content-end" id="navigation">
        	    <ul class="navbar-nav">

                <li class="nav-item">
                  <%= link_to "Your background", backgrounds_path, class:"nav-link" %>

                </li>

                <li class="nav-item">
                  <%#= link_to "Present illness", present_illnesses_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Review of System", reviews_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Past Medical History", past_medical_histories_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%#= link_to "Patients", root_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%#= link_to "Language", root_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <% if user_signed_in? %>
                    <%= link_to "Account setting", edit_user_registration_path, class:"nav-link" %>
                  <% else %>
                    <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
                  <% end %>
                </li>
                <li class="nav-item">
                  <% if user_signed_in? %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link" %>
                  <% else %>
                    <%= link_to "Log in", new_user_session_path, class:"nav-link" %>
                  <% end %>
                </li>
                <li class="nav-item active">
                    <%= link_to "HOME", root_path, class:"nav-link" %>
                </li>
              </ul>
            </div>
        </div>
    </nav>

  </head>


  <body>

    <header>
    </header>



    <%= yield %>



    <footer>
      <p>運営会社 株式会社 Dr.Tokyo</p>
      <p>© 2017-2018 Copyright Dr.Tokyo Corp.</p>
    </footer>

  </body>
</html>